In [6]:
import numpy as np


In [7]:
# 1D array from 1 to 10
arr1 = np.arange(1, 11)

# 2D array of size 3x3
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Array of zeros (4x4)
zeros_array = np.zeros((4, 4))

# Array of ones (2x5)
ones_array = np.ones((2, 5))

# Display arrays
print("1D Array:\n", arr1)
print("\n2D Array:\n", arr2)
print("\nZeros Array:\n", zeros_array)
print("\nOnes Array:\n", ones_array)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array:\n", array_2d)

# Shape
print("Shape:", array_2d.shape)

# Total elements
print("Total Elements:", array_2d.size)

# Data type
print("Data Type:", array_2d.dtype)

# Number of dimensions
print("Dimensions:", array_2d.ndim)

# Explanation
print("\nShape is important in AI because it tells us")
print("how data is organized for machine learning models.")

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Total Elements: 6
Data Type: int64
Dimensions: 2

Shape is important in AI because it tells us
how data is organized for machine learning models.


In [9]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Access elements
print("First Element:", arr[0])
print("Last Element:", arr[-1])
print("Third Element:", arr[2])

# Values greater than 30
print("Values greater than 30:", arr[arr > 30])

First Element: 10
Last Element: 60
Third Element: 30
Values greater than 30: [40 50 60]


In [10]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Elements from index 1 to 4
print("Slice 1:4 =", arr[1:5])

# Reverse array
print("Reversed Array =", arr[::-1])

# Alternate elements
print("Alternate Elements =", arr[::2])

# 3x3 matrix
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# First row
print("\nFirst Row:", matrix[0])

# Second column
print("Second Column:", matrix[:,1])

# Last two rows
print("Last Two Rows:\n", matrix[1:])

Slice 1:4 = [20 30 40 50]
Reversed Array = [60 50 40 30 20 10]
Alternate Elements = [10 30 50]

First Row: [1 2 3]
Second Column: [2 5 8]
Last Two Rows:
 [[4 5 6]
 [7 8 9]]


In [11]:
arr = np.array([1, 2, 3, 4, 5])

# Multiply by 5
print("Multiply by 5:", arr * 5)

# Add 10
print("Add 10:", arr + 10)

# Square elements
print("Squared:", arr ** 2)

# Explanation
print("\nVectorization makes calculations faster")
print("because operations are applied to all elements at once.")

Multiply by 5: [ 5 10 15 20 25]
Add 10: [11 12 13 14 15]
Squared: [ 1  4  9 16 25]

Vectorization makes calculations faster
because operations are applied to all elements at once.


In [12]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

# Add 10
print("Add 10:\n", arr + 10)

# Multiply by 2
print("\nMultiply by 2:\n", arr * 2)

# Explanation
print("\nBroadcasting allows operations on arrays")
print("of different sizes without loops.")

Add 10:
 [[11 12 13]
 [14 15 16]]

Multiply by 2:
 [[ 2  4  6]
 [ 8 10 12]]

Broadcasting allows operations on arrays
of different sizes without loops.


In [13]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("\nSubtraction:\n", A - B)

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]


In [14]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

# Matrix multiplication
result = np.dot(A, B)

print("Matrix Multiplication:\n", result)

# Transpose
print("\nTranspose of A:\n", A.T)

# Explanation
print("\nMatrix multiplication is used in neural networks")
print("to combine inputs, weights, and outputs.")

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Matrix multiplication is used in neural networks
to combine inputs, weights, and outputs.


In [15]:
# Random integer array
random_int = np.random.randint(1, 101, (4,4))

# Random decimal values
random_float = np.random.rand(4,4)

print("Random Integer Array:\n", random_int)
print("\nRandom Decimal Array:\n", random_float)

# Max, Min, Average
print("\nMaximum:", random_int.max())
print("Minimum:", random_int.min())
print("Average:", random_int.mean())

# Explanation
print("\nRandom numbers are important in AI")
print("for training, testing, and initializing models.")

Random Integer Array:
 [[45 71 49 84]
 [84 13 58 56]
 [87  2 35 34]
 [ 8 55 65 72]]

Random Decimal Array:
 [[0.26516686 0.86831124 0.35646693 0.87261481]
 [0.55763448 0.43979964 0.00578899 0.59149686]
 [0.48560837 0.42002271 0.65992508 0.42317303]
 [0.56118187 0.63954203 0.24460145 0.31811091]]

Maximum: 87
Minimum: 2
Average: 51.125

Random numbers are important in AI
for training, testing, and initializing models.


In [16]:
marks = np.array([45, 67, 89, 90, 76, 55, 32, 81, 95, 48])

# Average
print("Average Marks:", marks.mean())

# Highest
print("Highest Marks:", marks.max())

# Lowest
print("Lowest Marks:", marks.min())

# Above 80
print("Students Above 80:", np.sum(marks > 80))

# Failed below 50
print("Failed Students:", marks[marks < 50])

Average Marks: 67.8
Highest Marks: 95
Lowest Marks: 32
Students Above 80: 4
Failed Students: [45 32 48]


In [17]:
# Random image pixels
image = np.random.randint(0, 256, (5,5))

print("Image Pixels:\n", image)

# Brightest pixel
print("\nBrightest Pixel:", image.max())

# Darkest pixel
print("Darkest Pixel:", image.min())

# Shape
print("Image Shape:", image.shape)

# Explanation
print("\nAI reads images as arrays of pixel values.")

Image Pixels:
 [[225  31 239 207 225]
 [168  13 215 157   5]
 [118 249  19 218 148]
 [224 219   1  40 140]
 [ 99  29 131 136  14]]

Brightest Pixel: 249
Darkest Pixel: 1
Image Shape: (5, 5)

AI reads images as arrays of pixel values.


In [18]:
data = np.array([10, 20, 30, 40, 50])

# Normalization
normalized = (data - data.min()) / (data.max() - data.min())

print("Original Data:", data)
print("Normalized Data:", normalized)

# Explanation
print("\nNormalization improves AI performance")
print("by scaling values into a similar range.")

Original Data: [10 20 30 40 50]
Normalized Data: [0.   0.25 0.5  0.75 1.  ]

Normalization improves AI performance
by scaling values into a similar range.


In [19]:
# Dataset: Age, Salary, Purchased
dataset = np.array([
    [25, 50000, 1],
    [30, 60000, 0],
    [35, 65000, 1],
    [40, 70000, 0]
])

print("Dataset:\n", dataset)

# Input features
X = dataset[:, :2]

# Output labels
y = dataset[:, 2]

print("\nInput Features:\n", X)
print("\nOutput Labels:\n", y)

# Average salary
print("\nAverage Salary:", dataset[:,1].mean())

# Highest age
print("Highest Age:", dataset[:,0].max())

# Dataset shape
print("Dataset Shape:", dataset.shape)

Dataset:
 [[   25 50000     1]
 [   30 60000     0]
 [   35 65000     1]
 [   40 70000     0]]

Input Features:
 [[   25 50000]
 [   30 60000]
 [   35 65000]
 [   40 70000]]

Output Labels:
 [1 0 1 0]

Average Salary: 61250.0
Highest Age: 40
Dataset Shape: (4, 3)
